services:
  public-api:
    image: aidanmorgan/wordle-publicapi
    build:
      context: .
      dockerfile: Wordle.Api.Public/Dockerfile
      args:
        - BUILD_CONFIGURATION=Development
    env_file: 
      - .development.env
      - .sensitive.env
    environment:
      - ASPNETCORE_URLS=http://[::]:5100
    volumes:
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    ports:
      - 5100:5100
      
  private-api:
    image: aidanmorgan/wordle-privateapi
    build:
      context: .
      dockerfile: Wordle.Api.Private/Dockerfile
      args:
        - BUILD_CONFIGURATION=Development
    env_file:
      - .development.env
      - .sensitive.env
    environment:
      - ASPNETCORE_URLS=http://[::]:5200
    volumes:
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    ports:
      - 5200:5200
  
  event-handler:
    image: aidanmorgan/wordle-eventhandler
    build:
      context: .
      dockerfile: Wordle.Apps.GameEventProcessor/Dockerfile
      args:
        - BUILD_CONFIGURATION=Development
    env_file:
      - .development.env      
      - .sensitive.env
    volumes:
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    deploy:
      mode: replicated
      replicas: 3
  
  
  timeout-handler:
    image: aidanmorgan/wordle-timeouthandler
    build:
      context: .
      dockerfile: Wordle.Apps.TimeoutProcessor/Dockerfile
      args:
        - BUILD_CONFIGURATION=Development
    env_file:
      - .development.env
      - .sensitive.env
    volumes:
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    deploy:
      mode: replicated
      replicas: 3


  board-generator:
    image: aidanmorgan/wordle-boardgenerator
    
    build:
      context: .
      dockerfile: Wordle.Apps.BoardGenerator/Dockerfile
      args:
        - BUILD_CONFIGURATION=Development
    env_file:
      - .development.env
      - .sensitive.env
    volumes:
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
      - ./Wordle.Apps.BoardGenerator/deps:/usr/share/fonts:ro
    deploy:
      mode: replicated
      replicas: 3


