services:
  public-api:
    image: aidanmorgan/wordle-publicapi
    build:
      context: .
      dockerfile: Wordle.Api.Public/Dockerfile
      args:
        - BUILD_CONFIGURATION=Development
    env_file:
      - .development-docker.env
      - .sensitive-docker.env
    environment:
      - ASPNETCORE_URLS=http://[::]:5100
      - INSTANCE_ID=f14e672b-3912-4c98-9e67-da2612944151
    volumes:
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    ports:
      - 5100:5100
    links: 
      - activemq
      - postgres
    depends_on:
       postgres:
          condition: service_healthy
       activemq:
         condition: service_healthy

    networks:
      - wordle-local
      
  private-api:
    image: aidanmorgan/wordle-privateapi
    build:
      context: .
      dockerfile: Wordle.Api.Private/Dockerfile
      args:
        - BUILD_CONFIGURATION=Development
    env_file:
      - .development-docker.env
      - .sensitive-docker.env
    environment:
      - ASPNETCORE_URLS=http://[::]:5200
      - INSTANCE_ID=98456bad-464e-42d8-a0fc-48ea7d494ae5
    volumes:
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    ports:
      - 5200:5200
    links:
      - activemq
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_healthy
    networks:
      - wordle-local

  realtime-api:
    image: aidanmorgan/wordle-realtimeapi
    build:
      context: .
      dockerfile: Wordle.Api.Realtime/Dockerfile
      args:
        - BUILD_CONFIGURATION=Development
    env_file:
      - .development-docker.env
      - .sensitive-docker.env
    environment:
      - ASPNETCORE_URLS=http://[::]:5300
      - INSTANCE_ID=c596347c-e72f-4e61-9803-8dd407110872 
      - IMAGES_BASEDIRECTORY=/var/lib/wordle-images
    volumes:
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
      - images-data:/var/lib/wordle-images:r
    ports:
      - 5300:5300
    links:
      - activemq
      - postgres   
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_healthy
    networks:
      - wordle-local
  
  game-event-processor:
    image: aidanmorgan/wordle-gameeventprocessor
    build:
      context: .
      dockerfile: Wordle.Apps.GameEventProcessor/Dockerfile
      args:
        - BUILD_CONFIGURATION=Development
    env_file:
      - .development-docker.env
      - .sensitive-docker.env
    environment:
      - INSTANCE_ID=bb1bfeb6-8cf9-46cc-a87e-d4553e555662
    volumes:
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro  
    links:
      - activemq
      - postgres   
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_healthy
    networks:
      - wordle-local
  
  board-generator:
    image: aidanmorgan/wordle-boardgenerator
    build:
      context: .
      dockerfile: Wordle.Apps.BoardGenerator/Dockerfile
      args:
        - BUILD_CONFIGURATION=Development
    env_file:
      - .development-docker.env
      - .sensitive-docker.env
    environment:
      - IMAGES_BASEDIRECTORY=/var/lib/wordle-images
      - INSTANCE_ID=577c51ab-e2bc-4bc7-8cf6-e04b917076e4        
    volumes:
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
      - ./Wordle.Apps.BoardGenerator/deps:/usr/share/fonts:ro  
      - images-data:/var/lib/wordle-images:rw     
    links:
      - activemq
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_healthy
    networks:
      - wordle-local

  activemq:
    image: rmohr/activemq
    hostname: activemq-wordle
    env_file:
      - .development-docker.env
      - .sensitive-docker.env
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - ../config/activemq:/opt/activemq/conf:rw
      - activemq-data:/opt/activemq/data:rw
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:61616/ || exit 1"]
      interval: 5s
    networks:
      wordle-local:
        aliases:
          - activemq
          - wordle-activemq

  postgres:
    image: postgres:latest
    hostname: wordle-postgres
    env_file:
      - .development-docker.env
      - .sensitive-docker.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      wordle-local:
        aliases:
          - postgres
          - wordle-postgres



volumes:
  postgres-data:
  images-data:
  activemq-data:


networks:
  wordle-local:
    name: wordle-local
    external: true
